language: python

env: PORTAGE_GRPNAME=$USER PORTAGE_USERNAME=$USER USERLAND=GNU USE_EXPAND=USERLAND USE_EXPAND_HIDDEN=USERLAND

before_install:
  # Install development portage (it should have the latest suggestions)
  - "git clone git://git.overlays.gentoo.org/proj/portage.git $HOME/portage"

  # Set default config
  - "sudo mkdir /usr/share/portage"
  - "sudo ln -s $HOME/portage/cnf /usr/share/portage/config"

  # Create /usr/portage
  - "sudo mkdir /usr/portage"
  - "sudo chown $USER:$USER /usr/portage"

  # Populate /usr/portage
  - "rsync -arzp --safe-links rsync://rsync.gentoo.org/gentoo-portage/ /usr/portage/"
  - "mkdir /usr/portage/distfiles"

  # Set portage's profile
  #- "export USERLAND=GNU"
  #- "export USE_EXPAND=USERLAND"
  #- "export USE_EXPAND_HIDDEN=USERLAND"

script:
  - "$HOME/portage/bin/repoman -vx full"
  - "$HOME/portage/bin/repoman -vx full --without-mask"
  - "$HOME/portage/bin/repoman -vx full --include-dev --without-mask"